<a href="https://colab.research.google.com/github/mrshubhamjha/CODSOFT_CREDITCARDFRAUDDETECTION/blob/main/creditcard_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing dependencies

In [1]:
import numpy as nm
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

loading dataset

In [3]:
creditcard = pd.read_csv('creditcard.csv')

In [5]:
creditcard.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [6]:
creditcard.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
55546,47004,1.283418,0.354874,0.158519,0.607335,-0.186818,-0.865444,0.084609,-0.186195,0.042276,...,-0.310652,-0.887568,0.084508,-0.012270,0.267755,0.116476,-0.022729,0.027233,0.89,0.0
55547,47005,-0.969584,-0.514812,1.010076,-0.492493,-1.074442,0.812377,1.739011,0.069684,-0.741379,...,0.137958,-0.378729,0.989131,-0.311335,-0.302619,0.720578,-0.171671,0.034326,424.80,0.0
55548,47005,-0.448083,0.936043,1.308078,0.424255,0.141240,-0.224215,1.114183,-0.286478,-0.144553,...,0.084264,0.345878,-0.222427,0.052293,0.093368,-0.387899,-0.354380,-0.223041,55.75,0.0
55549,47005,0.616391,-0.770376,-0.306186,1.374006,-0.177289,0.186992,0.417697,0.073573,-0.009001,...,0.182098,-0.039148,-0.409170,-0.315762,0.626198,-0.254219,-0.042365,0.044234,293.00,0.0
55550,47005,-2.212795,0.701029,1.063799,1.449808,-1.045775,0.416184,-1.071689,-2.157124,0.014993,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
creditcard.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55551 entries, 0 to 55550
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    55551 non-null  int64
 1   V1      55551 non-null  float64
 2   V2      55551 non-null  float64
 3   V3      55551 non-null  float64
 4   V4      55551 non-null  float64
 5   V5      55551 non-null  float64
 6   V6      55551 non-null  float64
 7   V7      55551 non-null  float64
 8   V8      55551 non-null  float64
 9   V9      55551 non-null  float64
 10  V10     55551 non-null  float64
 11  V11     55551 non-null  float64
 12  V12     55551 non-null  float64
 13  V13     55551 non-null  float64
 14  V14     55551 non-null  float64
 15  V15     55550 non-null  float64
 16  V16     55550 non-null  float64
 17  V17     55550 non-null  float64
 18  V18     55550 non-null  float64
 19  V19     55550 non-null  float64
 20  V20     55550 non-null  float64
 21  V21     55550 non-null  float64
 22  V22     55550 non-null  float64
 23  V23     55550 non-null  float64
 24  V24     55550 non-null  float64
 25  V25     55550 non-null  float64
 26  V26     55550 non-null  float64
 27  V27     55550 non-null  float64
 28  V28     55550 non-null  float64
 29  Amount  55550 non-null  float64
 30  Class   55550 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 13.1 MB

In [8]:
creditcard.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [9]:
print(creditcard['V15'].mode())

0    1.069356
Name: V15, dtype: float64

In [10]:
print(creditcard['V15'].mode()[0])

1.06935589341597

In [12]:
creditcard['V15'].fillna(creditcard['V15'].mode()[0], inplace=True)

In [15]:
print(creditcard[['V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']].mode())

        V16       V17      V18       V19       V20       V21       V22  \
0 -0.255231 -1.072085  0.48511  0.271315  0.156089  0.007343  0.250886

      V23       V24      V25       V26       V27       V28
0 -0.3316  1.009952  0.23373 -0.824471  0.241305 -0.020359

In [17]:
import pandas as pd
columns_to_set_mode_to_zero = ['V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']
mode_values = creditcard[columns_to_set_mode_to_zero].mode().iloc[0]
creditcard[columns_to_set_mode_to_zero] = creditcard[columns_to_set_mode_to_zero].fillna(0)
print(creditcard.head())

   Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010

        V26       V27       V28  Amount  Class
0 -0.189115  0.133558 -0.021053  149.62    0.0
1  0.125895 -0.008983  0.014724    2.69    0.0
2 -0.139097 -0.055353 -0.059752  378.66    0.0
3 -0.221929  0.062723  0.061458  123.50    0.0
4  0.502292  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [18]:
creditcard.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    1
Class     1
dtype: int64

In [19]:
print(creditcard['Amount'].mode())

0    1.0
Name: Amount, dtype: float64

In [20]:
print(creditcard['Amount'].mode()[0])

1.0

In [21]:
creditcard['Amount'].fillna(creditcard['Amount'].mode()[0], inplace=True)

In [22]:
print(creditcard['Class'].mode())

0    0.0
Name: Class, dtype: float64

In [23]:
print(creditcard['Class'].mode()[0])

0.0

In [24]:
creditcard['Class'].fillna(creditcard['Class'].mode()[0], inplace=True)

In [25]:
creditcard.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [26]:
creditcard['Class'].value_counts()

0.0    55395
1.0      156
Name: Class, dtype: int64

In [27]:
legit = creditcard[creditcard.Class == 0]
fraud = creditcard[creditcard.Class == 1]

In [28]:
print(legit.shape)
print(fraud.shape)

(55395, 31)
(156, 31)

In [29]:
legit.Amount.describe()

count    55395.000000
mean        94.701505
std        257.028229
min          0.000000
25%          7.680000
50%         25.790000
75%         86.905000
max      12910.930000
Name: Amount, dtype: float64

In [30]:
fraud.Amount.describe()

count     156.000000
mean       95.758013
std       228.178528
min         0.000000
25%         1.000000
50%         4.930000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [31]:
#comparing values for both transactions
creditcard.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,30601.062948,-0.222710,-0.018459,0.721313,0.161122,-0.244556,0.107566,-0.096472,0.045202,0.092668,...,0.046437,-0.031321,-0.106870,-0.038112,0.007273,0.134522,0.020398,0.002097,0.004102,94.701505
1.0,27835.794872,-7.345427,5.255872,-9.922599,5.709553,-5.426307,-2.204159,-7.736462,3.560034,-3.453697,...,0.449731,0.881689,-0.211806,-0.275513,-0.088146,0.239724,0.127377,0.580843,0.031086,95.758013

In [32]:
legit_sample = legit.sample(n=156)

In [34]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [35]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
18027,29127,-2.696502,-0.040324,0.825282,-2.546866,-0.381831,0.175854,-0.328711,0.568492,1.518414,...,0.029399,0.153660,0.134932,-1.050503,0.410293,-0.054857,-1.013146,0.779141,25.90,0.0
53563,46047,1.003033,-0.216858,0.907661,1.468614,-0.536590,0.620739,-0.445819,0.317951,0.627050,...,-0.012334,0.209608,-0.115051,0.052073,0.566018,-0.279030,0.061272,0.018758,46.00,0.0
24844,33408,-2.134365,1.144015,-0.544244,-2.298052,-0.518294,0.217449,0.018768,1.329479,0.329828,...,-0.017744,-0.107702,-0.036461,-1.143432,0.313601,-0.951406,-0.108437,-0.180686,88.97,0.0
7961,10979,1.270792,-0.466152,0.365816,-0.525627,-0.683161,0.022055,-1.011399,0.080285,0.447692,...,0.187797,0.684360,-0.147915,-0.403501,0.386381,-0.093228,0.015917,0.023723,39.00,0.0
33571,37288,-2.531263,-2.833413,1.663414,-2.620575,0.946036,-1.854859,-1.253933,0.179521,-2.079213,...,-0.100738,-0.440163,0.300093,-0.108009,0.647292,-0.437832,-0.257490,0.385211,50.00,0.0

In [36]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
52521,45501,1.001992,0.047938,-0.349002,1.493958,0.186939,0.190966,-0.001112,0.147140,0.580415,...,-0.334417,-1.014315,-0.128427,-0.946242,0.456090,-0.453206,0.046627,0.064698,105.99,1.0
52584,45541,-1.519244,2.308492,-1.503599,2.064101,-1.000845,-1.016897,-2.059731,-0.275166,-1.562206,...,1.307871,0.102826,-0.017746,0.149696,-0.096602,-0.369115,-0.019244,-0.208319,1.00,1.0
53591,46057,-1.309441,1.786495,-1.371070,1.214335,-0.336642,-1.390120,-1.709109,0.667748,-1.699809,...,0.533521,-0.022180,-0.299556,-0.226416,0.364360,-0.475102,0.571426,0.293426,1.00,1.0
53794,46149,-1.346509,2.132431,-1.854355,2.116998,-1.070378,-1.092671,-2.230986,1.036425,-1.895516,...,0.609508,0.202874,-0.060791,-0.186733,-0.017401,-0.283751,0.395451,0.233139,1.00,1.0
55401,46925,-0.481531,1.059542,0.647117,0.905586,0.819368,-0.091184,0.504135,0.161064,-0.765054,...,0.070633,0.192491,-0.174659,-0.438908,0.239259,-0.217823,-0.072852,0.010463,1.00,1.0

In [37]:
new_dataset['Class'].value_counts()

0.0    156
1.0    156
Name: Class, dtype: int64

In [38]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,31391.717949,-0.122101,-0.208749,0.859309,0.240951,-0.162138,0.093883,-0.204373,0.041474,0.074991,...,0.093695,-0.014844,-0.015764,-0.018844,0.011348,0.123784,-0.032245,-0.016758,0.012420,92.603141
1.0,27835.794872,-7.345427,5.255872,-9.922599,5.709553,-5.426307,-2.204159,-7.736462,3.560034,-3.453697,...,0.449731,0.881689,-0.211806,-0.275513,-0.088146,0.239724,0.127377,0.580843,0.031086,95.758013

splitting data

In [41]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [42]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
18027  29127 -2.696502 -0.040324  0.825282 -2.546866 -0.381831  0.175854
53563  46047  1.003033 -0.216858  0.907661  1.468614 -0.536590  0.620739
24844  33408 -2.134365  1.144015 -0.544244 -2.298052 -0.518294  0.217449
7961   10979  1.270792 -0.466152  0.365816 -0.525627 -0.683161  0.022055
33571  37288 -2.531263 -2.833413  1.663414 -2.620575  0.946036 -1.854859
...      ...       ...       ...       ...       ...       ...       ...
52521  45501  1.001992  0.047938 -0.349002  1.493958  0.186939  0.190966
52584  45541 -1.519244  2.308492 -1.503599  2.064101 -1.000845 -1.016897
53591  46057 -1.309441  1.786495 -1.371070  1.214335 -0.336642 -1.390120
53794  46149 -1.346509  2.132431 -1.854355  2.116998 -1.070378 -1.092671
55401  46925 -0.481531  1.059542  0.647117  0.905586  0.819368 -0.091184

             V7        V8        V9  ...       V20       V21       V22  \
18027 -0.328711  0.568492  1.518414  ... -0.519317  0.029399  0.153660
53563 -0.445819  0.317951  0.627050  ... -0.120124 -0.012334  0.209608
24844  0.018768  1.329479  0.329828  ... -0.462133 -0.017744 -0.107702
7961  -1.011399  0.080285  0.447692  ...  0.114620  0.187797  0.684360
33571 -1.253933  0.179521 -2.079213  ... -0.328517 -0.100738 -0.440163
...         ...       ...       ...  ...       ...       ...       ...
52521 -0.001112  0.147140  0.580415  ...  0.016004 -0.334417 -1.014315
52584 -2.059731 -0.275166 -1.562206  ...  0.175019  1.307871  0.102826
53591 -1.709109  0.667748 -1.699809  ...  0.253464  0.533521 -0.022180
53794 -2.230986  1.036425 -1.895516  ...  0.221919  0.609508  0.202874
55401  0.504135  0.161064 -0.765054  ... -0.042515  0.070633  0.192491

            V23       V24       V25       V26       V27       V28  Amount
18027  0.134932 -1.050503  0.410293 -0.054857 -1.013146  0.779141   25.90
53563 -0.115051  0.052073  0.566018 -0.279030  0.061272  0.018758   46.00
24844 -0.036461 -1.143432  0.313601 -0.951406 -0.108437 -0.180686   88.97
7961  -0.147915 -0.403501  0.386381 -0.093228  0.015917  0.023723   39.00
33571  0.300093 -0.108009  0.647292 -0.437832 -0.257490  0.385211   50.00
...         ...       ...       ...       ...       ...       ...     ...
52521 -0.128427 -0.946242  0.456090 -0.453206  0.046627  0.064698  105.99
52584 -0.017746  0.149696 -0.096602 -0.369115 -0.019244 -0.208319    1.00
53591 -0.299556 -0.226416  0.364360 -0.475102  0.571426  0.293426    1.00
53794 -0.060791 -0.186733 -0.017401 -0.283751  0.395451  0.233139    1.00
55401 -0.174659 -0.438908  0.239259 -0.217823 -0.072852  0.010463    1.00

[312 rows x 30 columns]

In [43]:
print(Y)

18027    0.0
53563    0.0
24844    0.0
7961     0.0
33571    0.0
        ...
52521    1.0
52584    1.0
53591    1.0
53794    1.0
55401    1.0
Name: Class, Length: 312, dtype: float64

In [46]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

In [47]:
print(X.shape, X_train.shape, X_test.shape)

(312, 30) (249, 30) (63, 30)

logistic regression model

In [48]:
model = LogisticRegression()

In [49]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

accuracy

In [50]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [51]:
print('Accuracy on Training data ', training_data_accuracy)

Accuracy on Training data  0.9718875502008032

In [53]:
# accuracy on test data
X_test_prediction= model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [54]:
print('Accuracy score on Test Data:',test_data_accuracy)

Accuracy score on Test Data: 0.9523809523809523